xray:
  red:
    - minecraft:red_concrete
    - minecraft:red_wool
    - minecraft:crimson_stem
    - minecraft:tnt
  orange:
    - minecraft:orange_concrete
    - minecraft:orange_wool
    - minecraft:waxed_copper_block
  blue:
    - minecraft:blue_concrete
    - minecraft:blue_wool
    - minecraft:sculk
    - minecraft:blue_shulker_box
    - minecraft:stripped_warped_hyphae
    - minecraft:light_blue_stained_glass
  green:
    - minecraft:green_concrete
    - minecraft:green_wool
    - minecraft:lime_concrete
    - minecraft:lime_wool
    - minecraft:slime_block
    - minecraft:spruce_leaves
    - minecraft:mangrove_leaves
    - minecraft:green_concrete
    - minecraft:melon_block
    - minecraft:waxed_oxidized_cut_copper_slab
  white:
    - minecraft:white_concrete
    - minecraft:white_wool
    - minecraft:white_glazed_terracotta
    - minecraft:birch_wood
    - minecraft:cobweb
    - minecraft:iron_door
    - minecraft:iron_bars
  brown:
    - minecraft:brown_concrete
    - minecraft:brown_wool
    - minecraft:crafting_table
    - minecraft:spruce_trapdoor
    - minecraft:spruce_log
    - minecraft:brown_concrete_powder
    - minecraft:mangrove_wood
    - minecraft:bookshelf
    - minecraft:oak_slab
    - minecraft:oak_stairs
    - minecraft:lectern
    - minecraft:ladder
  yellow:
    - minecraft:yellow_concrete
    - minecraft:yellow_wool
    - minecraft:hay_block
    - minecraft:sand
  purple:
    - minecraft:purple_concrete
    - minecraft:purple_wool
replacements:
  - bounding-box:
      start: -20, 67, -20
      end: 20, 72, 20
    find:
      - minecraft:purple_glazed_terracotta
    replace-with:
      - minecraft:brown_concrete
      - minecraft:green_concrete
      - minecraft:blue_concrete
      - minecraft:purple_concrete
      - minecraft:white_concrete
      - minecraft:red_concrete
      - minecraft:orange_concrete
      - minecraft:yellow_concrete
  - bounding-box:
      start: -22, 68, -20
      end: 20, 72, 20
    find:
      - minecraft:yellow_glazed_terracotta
    replace-with:
      - minecraft:tnt
      - minecraft:waxed_copper_block
      - minecraft:blue_shulker_box
      - minecraft:melon_block
      - minecraft:birch_wood
      - minecraft:crafting_table
      - minecraft:hay_block